USE MARFARMA_DB;
GO

BULK INSERT STG_CLIENTES
FROM 'E:\MARFARMA_EF\03_DATASET\datos\MARFARMA_CLIENTES.csv'
WITH (
    FORMAT = 'CSV',
    FIRSTROW = 2,
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '\n',
    CODEPAGE = '65001'
);
GO
